baseURL = "https://notes.muthu.co/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Engineering Notes"
theme = "ink-free"
[pagination]
  pagerSize = 10

[permalinks]
  posts = "/:year/:month/:title"

[params]
	subtitle = "Thoughts and Ideas on AI by Muthukrishnan"

	# Optional 64x64 avatar image.
	avatar = "/avatar.jpeg"

	featherIconsCDN = false
	mermaidCDN = "https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.esm.min.mjs"

	# Site color - dark/light/auto
	mode = "auto"

	# Enable a table of contents:
	# Either "static"/true, "floating", "both", or "none" (default: static)
	# The floating TOC dissapears on mobile and adds 200px vertical space
	toc = "none"
	# Whether to truncate everything but H1/H2 headings if the last element in a TOC isn't visible. Enabled by default
	enableTocTrunate = true

	# Max tags
	maxTags = 7

	# Define words per minute to approximate reading time
	wpm = 250

	# For statistics, we can compare the total word count against a book of your choice
	statisticsEnabled = true
	referenceBookWords = 95000.0
	referenceBook = "Artificial Intelligence: A Modern Approach"
	referenceAuthor = "Stuart Russell & Peter Norvig"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Resume"
url = "/resume"
weight = 4

[[menu.main]]
name = "Tags & Stats"
url = "/tags"
weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/muthuspark/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/krimuthu/"

[taxonomies]
   tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "github"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2

[caches]
  [caches.images]
    dir = ':cacheDir/images'